server:
  port: 8088
  servlet:
    context-path: /api
#    context-path:

mybatis-plus:
  # 对应的 XML 文件位置
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.ruoyi.**.domain
  # 针对 typeAliasesPackage，如果配置了该属性，则仅仅会扫描路径下以该类作为父类的域对象
  #typeAliasesSuperType: Class<?>
  # 如果配置了该属性，SqlSessionFactoryBean 会把该包下面的类注册为对应的 TypeHandler
  #typeHandlersPackage: null
  # 如果配置了该属性，会将路径下的枚举类进行注入，让实体类字段能够简单快捷的使用枚举属性
  #typeEnumsPackage: null
  # 启动时是否检查 MyBatis XML 文件的存在，默认不检查
  checkConfigLocation: false
  # 通过该属性可指定 MyBatis 的执行器，MyBatis 的执行器总共有三种：
  # SIMPLE：该执行器类型不做特殊的事情，为每个语句的执行创建一个新的预处理语句（PreparedStatement）
  # REUSE：该执行器类型会复用预处理语句（PreparedStatement）
  # BATCH：该执行器类型会批量执行所有的更新语句
  executorType: SIMPLE
  # 指定外部化 MyBatis Properties 配置，通过该配置可以抽离配置，实现不同环境的配置部署
  configurationProperties: null
  configuration:
    # 自动驼峰命名规则（camel case）映射
    # 如果您的数据库命名符合规则无需使用 @TableField 注解指定数据库字段名
    mapUnderscoreToCamelCase: true
    # 默认枚举处理类,如果配置了该属性,枚举将统一使用指定处理器进行处理
    # org.apache.ibatis.type.EnumTypeHandler : 存储枚举的名称
    # org.apache.ibatis.type.EnumOrdinalTypeHandler : 存储枚举的索引
    # com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler : 枚举类需要实现IEnum接口或字段标记@EnumValue注解.
    defaultEnumTypeHandler: org.apache.ibatis.type.EnumTypeHandler
    # 当设置为 true 的时候，懒加载的对象可能被任何懒属性全部加载，否则，每个属性都按需加载。需要和 lazyLoadingEnabled 一起使用。
    aggressiveLazyLoading: true
    # MyBatis 自动映射策略
    # NONE：不启用自动映射
    # PARTIAL：只对非嵌套的 resultMap 进行自动映射
    # FULL：对所有的 resultMap 都进行自动映射
    autoMappingBehavior: PARTIAL
    # MyBatis 自动映射时未知列或未知属性处理策
    # NONE：不做任何处理 (默认值)
    # WARNING：以日志的形式打印相关警告信息
    # FAILING：当作映射失败处理，并抛出异常和详细信息
    autoMappingUnknownColumnBehavior: NONE
    # Mybatis一级缓存，默认为 SESSION
    # SESSION session级别缓存，同一个session相同查询语句不会再次查询数据库
    # STATEMENT 关闭一级缓存
    localCacheScope: SESSION
    # 开启Mybatis二级缓存，默认为 true
    cacheEnabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    # 是否打印 Logo banner
    banner: true
    # 是否初始化 SqlRunner
    enableSqlRunner: false
    dbConfig:
      # 主键类型
      # AUTO 数据库ID自增
      # NONE 空
      # INPUT 用户输入ID
      # ASSIGN_ID 全局唯一ID
      # ASSIGN_UUID 全局唯一ID UUID
      idType: AUTO
      # 表名前缀
      tablePrefix: null
      # 字段 format,例: %s,(对主键无效)
      columnFormat: null
      # 表名是否使用驼峰转下划线命名,只对表名生效
      tableUnderline: true
      # 大写命名,对表名和字段名均生效
      capitalMode: false
      # 全局的entity的逻辑删除字段属性名
      logicDeleteField: null
      # 逻辑已删除值
      logicDeleteValue: 1
      # 逻辑未删除值
      logicNotDeleteValue: 0
      # 字段验证策略之 insert,在 insert 的时候的字段验证策略
      # IGNORED 忽略判断
      # NOT_NULL 非NULL判断
      # NOT_EMPTY 非空判断(只对字符串类型字段,其他类型字段依然为非NULL判断)
      # DEFAULT 默认的,一般只用于注解里
      # NEVER 不加入 SQL
      insertStrategy: NOT_NULL
      # 字段验证策略之 update,在 update 的时候的字段验证策略
      updateStrategy: NOT_NULL
      # 字段验证策略之 select,在 select 的时候的字段验证策略既 wrapper 根据内部 entity 生成的 where 条件
      selectStrategy: NOT_NULL
spring:
  profiles:
    active: dev

# 微信开放平台 appid
wx:
  open:
    app_id: wxed9954c01bb89b47
  # 微信开放平台 appsecret
    app_secret: a7482517235173ddb4083788de60b90e
  # 微信开放平台 重定向url
    redirect_url: http://guli.shop/api/ucenter/wx/callback
# 支付宝沙箱
alipay:
  app-id: 2016101800716285
  private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCVNHQdFPNkckBhqV9Z5hOBvi9LJlTimbJ8YQhyR85270RO8XEApGl/h4pBXpPFDCX36m7r1UswLIN/+a0qXW2b5yFXTHfzbWaohqfkqJew0cBMcaSHBS8ssIfILwSi2GoCT223pD9hYd4bsqtL2C8q3cwy8SkfjRNXbQsAW77HRUaYQheRAsNf/XfbQhD7gD0C2KdL5HAeuOQqlLZv+TTbSgHD6/EvjSfNIEMJAOg5ZVWSCAETt904S+x3bLzETkeOLo3d7dyFz7QcBnYHSSXFRmqFPKdgSnUOaU4CdYZ399dwRFZMY4jNrZmmBNEQDA1W8SGrqso+2u0gs+Rr/BVPAgMBAAECggEADTrIbOe1qRtkUASHmt4GrsNhSCWO80SzicnEyPVK/kq64NERtv/dBtzKyn8LVTZ9i1zzFuAjuZLI2ikWTKJaHK/Cyg3SuPfjWWAPNPwp7xi6F00gTISOKUVB1OMuYw4TYD8QuG7M2+KkogoWnDQAAqoF+CJgBhcpNuBJUG/SG7MK4ie6zbCUkZCjmrryFdfxpfUUZhV+kcK7VFIpBAsU8lSEb7aQrxqfLT2mKS00NFq+fMGGs6dlL0KR1W4nBlxy4mdnz3uE7bY/zR0mVirlstGyI9skK4YW+nqWMdSU6idrMnaTTEhLhUZtOp3o6yJXx2YsG314rVX/mT7zTb4eEQKBgQDdGlT0CKw9MVofZmcz+SCcdtEj1s2xUsIz8qYKTeZl/eK9fXhm/CIoiPGU4hYDz2qvlqMRt02irPpCeriPRvBEBQT2NYLmCa6UhzQ8KJHkLlGD8ZdmMXbn+TBIKmlNmt/JHDDVyovradrAZqovJdouGMBbKlWYiOnt0DyyBH0hiQKBgQCswRUNy5eUwf2mSMa9FEIiEjshKjN76TPU9R/SftkCWKWocdhGU99gXkUso8uvWRCBnXhBNMMBYHcEm2Nn7WBtDXHrlh7oKDKtr0zPPpFgFnoI6jMyWfG0y36v62XAeYQxqkz1nCkfxApsTJBxf0No1gxR88K0vKbmlsvYXuMCFwKBgQC0L75l9h9v6yVYC5s1huSlvkroWyjcRuaPcUMRiLSoD8TVykfyHa40vI2sWKe6STHXkPqp+GljlnaI8Pwxf41U0YZeo/NeRyuoTZsrH6DthTXXQm6w0MTnfXN0jGOu4/VWLww5XsyyeFzWiZRNwhpRkMhKQ3DoU0PZE+gy52eWiQKBgCbuSEFYnStP4EqF4gugMhsdgqfBq+KDtkOKjgZQwbTOp15jcXq/0foUpIAf1XoJlzeudfgz3LJFu+yU2/0CuJU6z25o4UQuMuWDOMsHbZl61zuFE86ICHlW1pDseny6pbjPiRJcg8P92N95DaAWLunEOviI91rlnLMgToXPNFc3AoGAaOrtYW/gKJocDncM9tbAttqr9+h1dfu2xYqrlf1cBeFfTpbDVhPVYdUZBhoAU0BDQQ8yidz70BR+IrEzeKr7s7+fwSHx/I571s/NbR+y+ECohfXfB/GKi2O4T9CLpgyiTsPKrRzxh8VcGlWrB2Xn1O1aklnkkH9c5Xq1oHDZkVA=
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAk2bx/g8e4nl112EtPbH/9+tEpts5h7yiG1KTMRdv+N4ieGIlX03zg6QYVEGeD/l/kfUtQcf6xeNuyA0DmpTbxLG1HJDI2/5G/dxhvRIP/LOvozQ0Z0UiUHKoKiLVtThemghmkx4VBvow754yaMJuNOCSK55l4mXG/7TBWGJN/oYGw3GrFdoePV4zmL5WLddJmI+uIvISXW7Orpe0zAFUFtBChepsArpZ8V4dBXinXTGmu3kkplhtXBO5VseoSygZNyYn3wiK8NT00X6xvi5BrRE5ERamP5JbxIENQ6rKl7e5FDeUfzFhJtskuGKORq/u0Ai1MEB7WcDREm7G94ofsQIDAQAB
  gateway: https://openapi.alipaydev.com/gateway.do
